// ---------------------------------------------------------------------------
// Express routes for the Social Report feature. Mounted from app.ts via
// registerSocialReportRoutes(app, { getDatabaseData, saveDatabaseData }) —
// reads/writes the exact same app_state blob as every other feature in this
// app (Supabase in production, src/db_store.json locally), under a new
// top-level "social_report" key.
// ---------------------------------------------------------------------------
import type { Express, Request, Response } from "express";
import { requireAuth } from "../auth";
import {
  isGoogleOAuthConfigured,
  buildGoogleAuthUrl,
  signOAuthState,
  verifyOAuthState,
  exchangeCodeForTokens,
  saveGoogleTokenIntoState,
  isGoogleConnected,
} from "./googleAuth";
import { getYoutubeChannelId } from "./youtube";
import { isGoogleAdsConfigured } from "./googleAds";
import { runSync, computeWeeklyReport } from "./syncEngine";
import { emptySocialReportState, SocialReportState } from "./types";

interface Deps {
  getDatabaseData: () => Promise<any>;
  saveDatabaseData: (data: any) => Promise<void>;
}

function readSocialReportState(fullStore: any): SocialReportState {
  return fullStore.social_report
    ? { ...emptySocialReportState(), ...fullStore.social_report }
    : emptySocialReportState();
}

async function withState<T>(
  deps: Deps,
  fn: (state: SocialReportState) => Promise<T>,
  persist: boolean
): Promise<T> {
  const fullStore = await deps.getDatabaseData();
  const state = readSocialReportState(fullStore);
  const result = await fn(state);
  if (persist) {
    fullStore.social_report = state;
    await deps.saveDatabaseData(fullStore);
  }
  return result;
}

export function registerSocialReportRoutes(app: Express, deps: Deps): void {
  // GET /api/social-report/status — Admin-only setup/health panel: what's
  // configured via env vars vs still missing, whether Google is connected,
  // and the result of the last sync run.
  app.get("/api/social-report/status", requireAuth("Admin"), async (_req: Request, res: Response) => {
    try {
      let channelIdConfigured = true;
      try {
        getYoutubeChannelId();
      } catch {
        channelIdConfigured = false;
      }

      const status = await withState(
        deps,
        async (state) => ({
          googleOAuthConfigured: isGoogleOAuthConfigured(),
          channelIdConfigured,
          googleAdsConfigured: isGoogleAdsConfigured(),
          connected: isGoogleConnected(state),
          connectedAt: state.oauth?.google?.connectedAt || null,
          connectedBy: state.oauth?.google?.connectedBy || null,
          lastSyncedAt: state.lastSyncedAt,
          lastSyncLog: state.lastSyncLog,
          videoCount: new Set(state.snapshots.map((s) => s.videoId)).size,
        }),
        false
      );
      return res.json({ success: true, status });
    } catch (err: any) {
      return res.status(500).json({ error: err.message || "Lỗi đọc trạng thái Social Report." });
    }
  });

  // GET /api/social-report/oauth/google/start — Admin-only. Returns the
  // Google consent URL; the frontend navigates the whole browser there
  // (window.location.href), since a fetch()-initiated redirect can't carry
  // the browser to Google's login page.
  app.get("/api/social-report/oauth/google/start", requireAuth("Admin"), async (req: Request, res: Response) => {
    try {
      if (!isGoogleOAuthConfigured()) {
        return res.status(503).json({
          error: "Chưa cấu hình GOOGLE_OAUTH_CLIENT_ID/GOOGLE_OAUTH_CLIENT_SECRET/GOOGLE_OAUTH_REDIRECT_URI.",
        });
      }
      const session = (req as any).session as { username: string };
      const state = signOAuthState(session.username);
      const authUrl = buildGoogleAuthUrl(state);
      return res.json({ success: true, authUrl });
    } catch (err: any) {
      return res.status(500).json({ error: err.message || "Lỗi tạo đường dẫn xác thực Google." });
    }
  });

  // GET /api/social-report/oauth/google/callback — hit by Google's redirect,
  // so it cannot carry our Authorization header. Protected instead by the
  // signed `state` param (proves an Admin started this flow in the last 10
  // minutes) generated by the /start route above.
  app.get("/api/social-report/oauth/google/callback", async (req: Request, res: Response) => {
    const { code, state, error } = req.query as { code?: string; state?: string; error?: string };
    if (error) {
      return res.redirect(`/?social_oauth=error&message=${encodeURIComponent(String(error))}`);
    }
    const verified = verifyOAuthState(state);
    if (!verified) {
      return res.redirect(`/?social_oauth=error&message=${encodeURIComponent("Phiên xác thực đã hết hạn, vui lòng thử lại.")}`);
    }
    if (!code) {
      return res.redirect(`/?social_oauth=error&message=${encodeURIComponent("Thiếu mã xác thực từ Google.")}`);
    }
    try {
      const { refreshToken, scope } = await exchangeCodeForTokens(String(code));
      await withState(
        deps,
        async (socialState) => {
          saveGoogleTokenIntoState(socialState, refreshToken, scope, verified.username);
        },
        true
      );
      return res.redirect("/?social_oauth=success");
    } catch (err: any) {
      // Log the real error server-side only — never put a raw error message
      // (from Google's OAuth client / gaxios) into this redirect's query
      // string. This repo is public and this URL can end up in browser
      // history/proxy logs, so it must never carry anything that could
      // echo request details back (e.g. a library formatting an error
      // around the token request body).
      console.error("Google OAuth callback error:", err);
      const safeMessage = err instanceof Error && err.message.startsWith("Google không trả về refresh_token")
        ? err.message // this one specific message is authored by us, not Google's client library — safe to show
        : "Lỗi kết nối Google. Vui lòng thử lại hoặc liên hệ Admin.";
      return res.redirect(`/?social_oauth=error&message=${encodeURIComponent(safeMessage)}`);
    }
  });

  // POST /api/social-report/sync — Admin-only manual trigger, same sync run
  // the Friday cron uses (see GET /api/cron/social-report-sync below).
  app.post("/api/social-report/sync", requireAuth("Admin"), async (_req: Request, res: Response) => {
    try {
      const result = await withState(deps, (state) => runSync(state), true);
      return res.json({ success: true, ...result });
    } catch (err: any) {
      return res.status(500).json({ error: err.message || "Lỗi đồng bộ Social Report." });
    }
  });

  // GET /api/social-report/data — Admin-only for now (feature is temporarily
  // hidden from Editor/Viewer in the UI too — see App.tsx's REPORT_CATEGORIES
  // filter). Locked down here as well so the data isn't reachable by calling
  // the API directly while the UI hides it.
  app.get("/api/social-report/data", requireAuth("Admin"), async (_req: Request, res: Response) => {
    try {
      const { rows, lastSyncedAt } = await withState(
        deps,
        async (state) => ({ rows: computeWeeklyReport(state), lastSyncedAt: state.lastSyncedAt }),
        false
      );
      return res.json({ success: true, rows, lastSyncedAt });
    } catch (err: any) {
      return res.status(500).json({ error: err.message || "Lỗi đọc dữ liệu Social Report." });
    }
  });

  // GET /api/cron/social-report-sync — hit by Vercel Cron (see vercel.json).
  // Same CRON_SECRET bearer-token gate as GET /api/cron/weekly-backup, for
  // the same reason: Vercel Cron has no user session to authenticate as.
  // Scheduled for Monday morning rather than Friday — both YouTube Analytics
  // and Google Ads data need a few days to settle before a Friday's numbers
  // are stable (see the automation feasibility research this was built from).
  app.get("/api/cron/social-report-sync", async (req: Request, res: Response) => {
    try {
      const expected = process.env.CRON_SECRET;
      if (!expected || req.headers.authorization !== `Bearer ${expected}`) {
        return res.status(401).json({ error: "Unauthorized" });
      }
      const result = await withState(deps, (state) => runSync(state), true);
      return res.json({ success: true, ...result });
    } catch (err: any) {
      console.error("GET /api/cron/social-report-sync error:", err);
      return res.status(500).json({ error: err.message || "Lỗi đồng bộ định kỳ Social Report." });
    }
  });
}
