import React, { useEffect, useState } from "react";
import { Music2, ExternalLink, CheckCircle2, AlertCircle } from "lucide-react";
import { safeFetchJson } from "../App";

interface AdvertiserCandidate {
  id: string;
  name: string;
  brandGuess: "Livotec" | "Karofi" | null;
}

// TikTok Ads (Business API) OAuth — a separate app/flow from the TikTok
// Login Kit connection in TiktokAccountsAdmin.tsx (that one is for organic
// Social Report insights). Replaces the old "paste an Advertiser ID + Access
// Token you generated by hand" setup in PaidAdsApiAccountsAdmin.tsx's TikTok
// tab. See GET /api/tiktok-ads/oauth/start|callback and POST
// /api/tiktok-ads/oauth/pending/:id/complete in src/server/app.ts.
export default function TiktokAdsConnectAdmin({ onImported }: { onImported: () => void }) {
  const [configured, setConfigured] = useState(true);
  const [isConnecting, setIsConnecting] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);

  const [pendingId, setPendingId] = useState<string | null>(null);
  const [advertisers, setAdvertisers] = useState<AdvertiserCandidate[]>([]);
  const [selected, setSelected] = useState<Record<string, { checked: boolean; brand: string }>>({});
  const [isLoadingPending, setIsLoadingPending] = useState(false);
  const [isImporting, setIsImporting] = useState(false);

  useEffect(() => {
    (async () => {
      try {
        const result = await safeFetchJson("/api/tiktok-ads/accounts");
        if (result.success) setConfigured(result.tiktokAdsOAuthConfigured !== false);
      } catch {
        // Non-fatal — see FacebookConnectAdmin's identical comment.
      }
    })();

    const params = new URLSearchParams(window.location.search);
    const id = params.get("ttAdsPendingId");
    if (id) {
      setPendingId(id);
      params.delete("ttAdsPendingId");
      window.history.replaceState({}, "", window.location.pathname + (params.toString() ? `?${params.toString()}` : ""));
    }
  }, []);

  useEffect(() => {
    if (!pendingId) return;
    (async () => {
      setIsLoadingPending(true);
      setMessage(null);
      try {
        const result = await safeFetchJson(`/api/oauth-pending/${encodeURIComponent(pendingId)}`);
        if (result.success && result.platform === "tiktok_ads") {
          const candidates: AdvertiserCandidate[] = result.candidates.advertisers || [];
          setAdvertisers(candidates);
          setSelected(Object.fromEntries(candidates.map((a) => [a.id, { checked: true, brand: a.brandGuess || "" }])));
        } else {
          setMessage({ type: "error", text: result.error || "Liên kết đã hết hạn — vui lòng kết nối lại." });
          setPendingId(null);
        }
      } catch (err: any) {
        setMessage({ type: "error", text: err.message || "Không tải được danh sách Advertiser." });
        setPendingId(null);
      } finally {
        setIsLoadingPending(false);
      }
    })();
  }, [pendingId]);

  async function handleConnect() {
    setIsConnecting(true);
    setMessage(null);
    try {
      const result = await safeFetchJson("/api/tiktok-ads/oauth/start");
      if (result.success && result.authorizeUrl) {
        window.location.href = result.authorizeUrl;
      } else {
        setMessage({ type: "error", text: result.error || "Không tạo được liên kết kết nối TikTok Ads." });
      }
    } catch (err: any) {
      setMessage({ type: "error", text: err.message || "Không tạo được liên kết kết nối TikTok Ads." });
    } finally {
      setIsConnecting(false);
    }
  }

  async function handleImport() {
    if (!pendingId) return;
    setIsImporting(true);
    setMessage(null);
    try {
      const result = await safeFetchJson(`/api/tiktok-ads/oauth/pending/${encodeURIComponent(pendingId)}/complete`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          advertisers: (Object.entries(selected) as [string, { checked: boolean; brand: string }][]).filter(([, v]) => v.checked).map(([id, v]) => ({ id, brand: v.brand || null })),
        }),
      });
      if (result.success) {
        setMessage({ type: "success", text: `Đã nhập ${result.advertisersImported} Advertiser.` });
        setPendingId(null);
        setAdvertisers([]);
        onImported();
      } else {
        setMessage({ type: "error", text: result.error || "Nhập kết nối thất bại." });
      }
    } catch (err: any) {
      setMessage({ type: "error", text: err.message || "Nhập kết nối thất bại." });
    } finally {
      setIsImporting(false);
    }
  }

  async function handleDismiss() {
    if (pendingId) await safeFetchJson(`/api/oauth-pending/${encodeURIComponent(pendingId)}`, { method: "DELETE" }).catch(() => {});
    setPendingId(null);
    setAdvertisers([]);
  }

  return (
    <div className="w-full animate-fade-in space-y-4 rounded-2xl border border-indigo-200 bg-white p-5 shadow-sm">
      <div className="flex items-center gap-2 border-b border-slate-100 pb-3">
        <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600">
          <Music2 className="h-4 w-4" />
        </div>
        <div>
          <h3 className="text-sm font-bold text-slate-900">Kết Nối TikTok Ads (Business API)</h3>
          <p className="text-[11px] text-slate-500">
            Đăng nhập TikTok Business một lần để lấy danh sách Advertiser bạn quản lý — chọn cái nào cần nhập vào bảng bên dưới,
            không cần tự dán Access Token nữa.
          </p>
        </div>
      </div>

      {!configured && (
        <div className="space-y-1 rounded-lg border border-amber-200 bg-amber-50 p-3 text-[11px] text-amber-800">
          <p className="font-semibold">Chưa cấu hình đầy đủ.</p>
          <p>
            Cần khai báo <code className="rounded bg-amber-100 px-1">TIKTOK_MARKETING_APP_ID</code>,{" "}
            <code className="rounded bg-amber-100 px-1">TIKTOK_MARKETING_APP_SECRET</code>,{" "}
            <code className="rounded bg-amber-100 px-1">TIKTOK_MARKETING_REDIRECT_URI</code> — xem hướng dẫn tạo app TikTok for
            Business trong .env.example. Đây là app khác hẳn app Login Kit đang dùng cho Social Report.
          </p>
        </div>
      )}

      {message && (
        <div
          className={`flex items-center gap-2 rounded-lg border p-2.5 text-xs ${
            message.type === "success" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-rose-200 bg-rose-50 text-rose-700"
          }`}
        >
          {message.type === "success" ? <CheckCircle2 className="h-3.5 w-3.5 shrink-0" /> : <AlertCircle className="h-3.5 w-3.5 shrink-0" />}
          {message.text}
        </div>
      )}

      {!pendingId ? (
        <button
          type="button"
          onClick={handleConnect}
          disabled={isConnecting || !configured}
          className="flex items-center gap-1.5 rounded-lg bg-indigo-600 px-4 py-2 text-xs font-bold text-white shadow-sm transition hover:bg-indigo-700 disabled:opacity-50"
        >
          <ExternalLink className="h-3.5 w-3.5" />
          {isConnecting ? "Đang tạo liên kết..." : "Kết nối TikTok Ads"}
        </button>
      ) : isLoadingPending ? (
        <p className="text-xs text-slate-400">Đang tải danh sách Advertiser...</p>
      ) : (
        <div className="space-y-4">
          <div>
            <p className="pb-1.5 text-xs font-bold text-slate-700">Advertiser ({advertisers.length})</p>
            <div className="space-y-1.5">
              {advertisers.length === 0 && <p className="text-xs text-slate-400">Tài khoản này không có Advertiser nào được ủy quyền.</p>}
              {advertisers.map((a) => (
                <label key={a.id} className="flex items-center gap-2 rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs">
                  <input
                    type="checkbox"
                    checked={selected[a.id]?.checked ?? false}
                    onChange={(e) => setSelected((prev) => ({ ...prev, [a.id]: { ...prev[a.id], checked: e.target.checked } }))}
                  />
                  <span className="flex-1 font-medium text-slate-700">
                    {a.name} <span className="text-slate-400">({a.id})</span>
                  </span>
                  <select
                    value={selected[a.id]?.brand || ""}
                    onChange={(e) => setSelected((prev) => ({ ...prev, [a.id]: { ...prev[a.id], brand: e.target.value } }))}
                    className={`rounded-lg border px-2 py-1 text-xs font-semibold ${selected[a.id]?.brand ? "border-slate-200 bg-slate-100" : "border-amber-300 bg-amber-50 text-amber-700"}`}
                  >
                    <option value="">Chưa xác định</option>
                    <option value="Livotec">Livotec</option>
                    <option value="Karofi">Karofi</option>
                  </select>
                </label>
              ))}
            </div>
          </div>

          <div className="flex gap-2">
            <button
              type="button"
              onClick={handleImport}
              disabled={isImporting}
              className="rounded-lg bg-indigo-600 px-4 py-2 text-xs font-bold text-white shadow-sm transition hover:bg-indigo-700 disabled:opacity-50"
            >
              {isImporting ? "Đang nhập..." : "Xác nhận & Nhập"}
            </button>
            <button type="button" onClick={handleDismiss} className="rounded-lg border border-slate-200 px-4 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50">
              Hủy
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
